#!/usr/bin/env bash
# Install nginx with the -y option to assume yes to prompts
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
