#!/usr/bin/env bash
# Does the following:
#   Create a file.
#   Display "To infinity and beyond" indefinitely.
#   Display "I hate the kill command" upon receiving a SIGTERM.
#   Display "Y U no love me?!" upon receiving a SIDn.

cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'cleanup' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done

