#!/usr/bin/env bash
# Displays numbers from 1 to 20 in the order below
# in the 4th loop "bad luck from China"
# in the 9th loop "bad luck from Japan"
# in the 17th loop "bad luck from Italy"

num=1

while [ $num -le 20 ]
do
    echo "$num"
    case "$num" in
	"4") echo "bad luck from China" ;;
	"9") echo "bad luck from Japan" ;;
	"17") echo "bad luck from Italy" ;;
    esac
    (( num++ ))
done
